### Authorize host admin
// @no-log 
// @no-cookie-jar
POST {{api}}/admin/hostlogin
Content-Type: application/json

{
    "email": "{{adminEmail}}",
    "password": "{{adminPassword}}"
}

> {%
	client.global.set('accessToken', response.body['accessToken']);
	client.global.set('refreshToken', response.body['refreshToken']);
%}

### Refresh authorization token
POST {{api}}/admin/refresh
Authorization: {{refreshToken}}
Content-Type: application/json

> {% client.global.set('accessToken', response.body['accessToken'])%}

### Get list of users
// @no-log 
// @no-cookie-jar
GET {{api}}/admin
Authorization: {{accessToken}}
Content-Type: application/json

### Get single admin/user
// @no-log 
// @no-cookie-jar
GET {{api}}/admin/{{userId}}
Authorization: {{accessToken}}
Content-Type: application/json

### Register to the service
// @no-log 
// @no-cookie-jar
POST {{api}}/admin
Authorization: {{accessToken}}
Content-Type: application/json

{
	"name": "Логист",
	"phone": "{{userPhone}}",
	"email": "{{userEmail}}",
	"type": 0
}

> {%
		client.global.set("userId", response.body['id'])
		client.global.set("userPhone", response.body['phone'])
 %}

### Login to service
POST {{api}}/admin/login
Authorization: {{accessToken}}
Content-Type: application/json

### Request verification code to signin by phone number
// @no-log 
// @no-cookie-jar
POST {{api}}/admin/signin?by=phone
Content-Type: application/json

{
	"phone": "{{userPhone}}"
}

> {% client.global.set('verificationCode', response.body['code']) %}

### Submit signin by supplying verification code
// @no-log 
// @no-cookie-jar
POST {{api}}/admin/signin?by=phone
Content-Type: application/json

{
	"phone": "{{userPhone}}",
	"code": "{{verificationCode}}"
}

> {%
	client.global.set('accessToken', response.body['accessToken'])
	client.global.set('refreshToken', response.body['refreshToken'])
	client.global.set('userId', response.body['user']['id'])
%}

### Request verification code to signin by email
// @no-log 
// @no-cookie-jar
POST {{api}}/admin/signin?by=email
Content-Type: application/json

{
	"email": "{{userEmail}}"
}

> {% client.global.set('verificationCode', response.body['code']) %}

### Submit signin by supplying verification code
// @no-log 
// @no-cookie-jar
POST {{api}}/admin/signin?by=email
Content-Type: application/json

{
	"email": "{{userEmail}}",
	"code": "{{verificationCode}}"
}

> {%
	client.global.set('accessToken', response.body['accessToken'])
	client.global.set('refreshToken', response.body['refreshToken'])
	client.global.set('userId', response.body['user']['id'])
%}

### Update admin information
// @no-log 
// @no-cookie-jar
PUT {{api}}/admin/{{userId}}
Authorization: {{accessToken}}
Content-Type: application/json

{
	"name": "Logist"
}

### Delete admin
// @no-log 
// @no-cookie-jar
DELETE {{api}}/admin/{{userId}}
Authorization: {{accessToken}}
Content-Type: application/json
