### Get bitrix order data
// @no-log
// @no-cookie-jar
GET {{api}}/bitrix/orders
Content-Type: application/json

### Update order data
// @no-log
// @no-cookie-jar
PUT {{api}}/bitrix/order/{{crmId}}
Content-Type: application/json

### Update bitrix order data
// @no-log
// @no-cookie-jar
PATCH {{api}}/bitrix/orders
Content-Type: application/json

### Delete order
// @no-log
// @no-cookie-jar
DELETE {{api}}/bitrix/order/{{crmId}}
Content-Type: application/json

### Test webhook from bitrix
// @no-log
// @no-cookie-jar
POST {{api}}/bitrix/webhook
Content-Type: application/json

{
		"event": "ONCRMDEALUPDATE",
		"data": { "FIELDS": { "ID": "{{crmId}}" } },
		"ts": "256325654982"
}
