### Get addresses
// @no-cookie-jar
GET {{api}}/reference/address?regions=1&search=М
Authorization: {{accessToken}}
Content-Type: application/json

### Search by some word
// @no-cookie-jar
GET {{api}}/reference/address?search={{addressTerm}}&full=true&provider=osm
Authorization: {{accessToken}}
Content-Type: application/json

### Get address data by nearest location coordinates
// @no-cookie-jar
POST {{api}}/reference/address/location
Authorization: {{accessToken}}
Content-Type: application/json

{
	"latitude": 55.81245949915643,
	"longitude": 37.613395053364286,
	"distance": 60
}

### Get transport extra fixtures
// @no-cookie-jar
GET {{api}}/reference/fixtures
Authorization: {{accessToken}}
Content-Type: application/json

### Get transport loading types
// @no-cookie-jar
GET {{api}}/reference/loading_types
Authorization: {{accessToken}}
Content-Type: application/json

### Get transport payloads
// @no-cookie-jar
GET {{api}}/reference/payloads
Authorization: {{accessToken}}
Content-Type: application/json

### Get payloads
// @no-cookie-jar
GET {{api}}/reference/payment_types
Authorization: {{accessToken}}
Content-Type: application/json

### Get risk classes
// @no-cookie-jar
GET {{api}}/reference/risk_classes
Authorization: {{accessToken}}
Content-Type: application/json

### Search by some word
// @no-cookie-jar
GET {{api}}/reference/auto_types
Authorization: {{accessToken}}
Content-Type: application/json

### Search by some word
// @no-cookie-jar
GET {{api}}/reference/brands
Authorization: {{accessToken}}
Content-Type: application/json

### Get all transport models
// @no-cookie-jar
GET {{api}}/reference/models
Authorization: {{accessToken}}
Content-Type: application/json

### Get transport brand model by brand id or value
// @no-cookie-jar
GET {{api}}/reference/models/1000
Authorization: {{accessToken}}
Content-Type: application/json
