### Get all transports
// @no-cookie-jar
GET {{api}}/transport
Authorization: {{accessToken}}
Content-Type: application/json

### Get all transports by filter
// @no-cookie-jar
POST {{api}}/transport/filter?full=true
Authorization: {{accessToken}}
Content-Type: application/json

{
	"cargoId": "{{companyId}}",
	"driverId": "{{driverId}}"
}

### Get single transport by id
// @no-cookie-jar
GET {{api}}/transport/{{transportId}}
Authorization: {{accessToken}}
Content-Type: application/json

### Create new transport record
// @no-cookie-jar
POST {{api}}/transport
Authorization: {{accessToken}}
Content-Type: application/json

{
	"cargoId": "{{companyId}}",
  "driverId": "{{driverId}}",
	"status": 1,
  "type": "2700",
  "extra_fixtures": [
  	"792",
    "794",
    "812"
  ],
  "brand": "946",
  "model": "4816",
  "registr_num": "мо 956 н 123",
  "prod_year": 2016,
  "payloads": [
    "64"
  	"2794",
 	],
  "payload_extra": false,
  "is_trailer": false,
  "is_dedicated": false,
  "sts": "51 1 2070 ",
  "weight_extra": 0,
  "volume_extra": 0,
  "weight": 30,
  "volume": 25,
  "length": 7,
  "width": 4,
  "height": 3,
  "polets": 40,
  "risk_classes": [
  	"14462",
    "14466",
    "14470"
  ],
  "loading_types": [
  	2
  ],
  "osago_number": "000 0000000000",
  "osago_date": "2026-07-12",
  "diag_num": "00000000000000000000",
  "diag_date": "2023-09-22",
  "info": "Китайстое авто.",
  "comments": "Haval"
}

> {%	client.global.set("transportId", response.body['id']); %}

### Update single transport by id
// @no-cookie-jar
PUT {{api}}/transport/{{transportId}}
Authorization: {{accessToken}}
Content-Type: application/json

{
    "isTrailer": false
}

### Get list of transports by driver id
// @no-cookie-jar
POST {{api}}/transport/driver/{{driverId}}
Authorization: {{accessToken}}
Content-Type: application/json

### Delete transport record
// @no-cookie-jar
DELETE {{api}}/transport/{{transportId}}
Authorization: {{accessToken}}
Content-Type: application/json

### Delete transport record
// @no-cookie-jar
POST {{api}}/transport/activate/{{transportId}}
Authorization: {{accessToken}}
Content-Type: application/json

### Delete transport image by id
// @no-cookie-jar
DELETE {{api}}/transport/image/{{transportId}}/{{imageId}}
Authorization: {{accessToken}}
Content-Type: application/json

### Upload transport image by transport id
// @no-cookie-jar
POST {{api}}/transport/image/{{transportId}}
Authorization: {{accessToken}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="front.jpg"

< ../resources/img/sample.jpg
--WebAppBoundary--

### Upload transport diagnostic document scan
// @no-cookie-jar
POST {{api}}/transport/diag/{{transportId}}
Authorization: {{accessToken}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="diagnostic.jpg"

< ../resources/img/sample.jpg
--WebAppBoundary--

### Upload transport osago document scan
// @no-cookie-jar
POST {{api}}/transport/osago/{{transportId}}
Authorization: {{accessToken}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="osago.jpg"

< ../resources/img/sample.jpg
--WebAppBoundary--
