const { companySeed } = require('./companySeed');
const { companyInnSeed } = require('./companyInnSeed');

const now = new Date();

const driverSeed = [
	{
		'id': 'cc00e758-7ae3-11ed-b003-8f261a76559a',
		'cargo_id': companySeed[0].id,
		'email': companySeed[0].email,
		'name': 'Андрей',
		'patronymic': 'Игоревич',
		'last_name': 'Миронов',
		'is_ready': true,
		'birth_date': '1985-08-20',
		'phone': companySeed[0].phone,
		'phone_second': '+7 998 222 30 40',
		'taxpayer_number': companySeed[0].taxpayer_number,
		'passport_serial_number': companySeed[0].passport_serial_number,
		'passport_given_date': companySeed[0].passport_given_date,
		'passport_subdivision_code': companySeed[0].passport_subdivision_code,
		'passport_issued_by': companySeed[0].passport_issued_by,
		'passport_registration_address': companySeed[0].passport_registration_address,
		'registration_address': companySeed[0].legal_address,
		'license_number': '82 256994',
		'license_date': '2024-01-27',
		'info': 'Не работаю по выходным',
		'latitude': 55.76526,
		'longitude': 37.73356,
		'created_at': now,
		'updated_at': now
	},
	{
		'id': 'e7bae7b4-7ae3-11ed-8994-13943af5ef1d',
		'cargo_id': companySeed[1].id,
		'email': companySeed[1].email,
		'name': 'Герман',
		'patronymic': 'Владимирович',
		'last_name': 'Кудрявцев',
		'is_ready': true,
		'birth_date': '1990-10-01',
		'phone': companySeed[1].phone,
		'phone_second': '+7 998 333 30 40',
		'taxpayer_number': companySeed[1].taxpayer_number,
		'passport_serial_number': companySeed[1].passport_serial_number,
		'passport_given_date': companySeed[1].passport_given_date,
		'passport_subdivision_code': companySeed[1].passport_subdivision_code,
		'passport_issued_by': companySeed[1].passport_issued_by,
		'passport_registration_address': companySeed[1].passport_registration_address,
		'registration_address': companySeed[1].legal_address,
		'license_number': '82 845214',
		'license_date': '2026-01-27',
		'info': '',
		'latitude': 56.32564,
		'longitude': 39.568963,
		'created_at': now,
		'updated_at': now
	},
	{
		'id': '043b0c84-7ae4-11ed-8cea-2b631f050ef4',
		'cargoinn_id': companyInnSeed[0].id,
		'email': companyInnSeed[0].email,
		'name': companyInnSeed[0].name,
		'patronymic': companyInnSeed[0].patronymic,
		'last_name': companyInnSeed[0].last_name,
		'is_ready': true,
		'birth_date': companyInnSeed[0].birth_date,
		'phone': companyInnSeed[0].phone,
		'phone_second': companyInnSeed[0].contact_phone,
		'taxpayer_number': companyInnSeed[0].taxpayer_number,
		'passport_serial_number': companyInnSeed[0].passport_serial_number,
		'passport_given_date': companyInnSeed[0].passport_given_date,
		'passport_subdivision_code': companyInnSeed[0].passport_subdivision_code,
		'passport_issued_by': companyInnSeed[0].passport_issued_by,
		'passport_registration_address': companyInnSeed[0].passport_registration_address,
		'registration_address': companyInnSeed[0].address,
		'license_number': '66 1473569',
		'license_date': '2026-01-27',
		'info': '',
		'latitude': 52.136548,
		'longitude': 38.567163,
		'created_at': now,
		'updated_at': now
	},
	{
		'id': '0c5fe484-7ae4-11ed-bc53-fb65e098db93',
		'cargoinn_id': companyInnSeed[1].id,
		'email': companyInnSeed[1].email,
		'name': companyInnSeed[1].name,
		'patronymic': companyInnSeed[1].patronymic,
		'last_name': companyInnSeed[1].last_name,
		'is_ready': true,
		'birth_date': companyInnSeed[1].birth_date,
		'phone': companyInnSeed[1].phone,
		'phone_second': companyInnSeed[1].personal_phone,
		'taxpayer_number': companyInnSeed[1].taxpayer_number,
		'passport_serial_number': companyInnSeed[1].passport_serial_number,
		'passport_given_date': companyInnSeed[1].passport_given_date,
		'passport_subdivision_code': companyInnSeed[1].passport_subdivision_code,
		'passport_issued_by': companyInnSeed[1].passport_issued_by,
		'passport_registration_address': companyInnSeed[1].passport_registration_address,
		'registration_address': companyInnSeed[1].address,
		'license_number': '66 1473569',
		'license_date': '2026-01-27',
		'info': '',
		'latitude': 54.136548,
		'longitude': 41.567163,
		'created_at': now,
		'updated_at': now
	}
];

module.exports = { driverSeed };
