import { faker }              from '@faker-js/faker';
import { GeneratorOptions }   from '@common/constants';
import * as interfaces        from '@common/interfaces';
import * as enums             from '@common/enums';
import * as dto               from '@api/dto';
import * as common            from './common';
import { generateTransports } from './transport';

type TDriverGeneratorResult = {
	driver: dto.DriverCreateDto,
	transports: dto.TransportCreateDto[]
};

const { COMPANY_DEFAULTS: { driver: DRIVER_DEFAULT_OPTIONS } } = GeneratorOptions;
const { lat, lon } = common;

/**@ignore*/
const randomDriverStatus = () => faker.helpers.arrayElement(common.DRIVER_STATUSES);

export async function generateDriver(
	company: interfaces.ICompany,
	options: interfaces.TDriverGenerateOptions = DRIVER_DEFAULT_OPTIONS
): Promise<TDriverGeneratorResult> {
	const { startPos, distanceDelta } = options;
	const name: string = faker.name.firstName('male');
	const patronymic: string = faker.name.middleName('male');
	const lastName: string = faker.name.lastName('male');
	const email: string = common.generateEmailAddress(name, lastName);

	const driver: dto.DriverCreateDto = {
		name,
		patronymic,
		lastName,
		email,
		cargoId:                     company.type === enums.CompanyType.ORG ? company.id : null,
		cargoinnId:                  company.type !== enums.CompanyType.ORG ? company.id : null,
		birthDate:                   faker.date.past(30),
		licenseNumber:               common.generateSerialNumber([2, 2, 7]),
		licenseDate:                 faker.date.future(5),
		passportGivenDate:           faker.date.past(10),
		passportIssuedBy:            common.generateAddress(),
		passportRegistrationAddress: common.generateAddress(),
		passportSerialNumber:        common.generateSerialNumber([3, 4]),
		passportSubdivisionCode:     common.generateSerialNumber([3, 3]),
		phone:                       company.phone,
		phoneSecond:                 company.contactPhone,
		address:                     common.generateAddress(),
		registrationAddress:         common.generateAddress(),
		status:                      randomDriverStatus(),
		isReady:                     true,
		latitude:                    lat(startPos.latitude, distanceDelta),
		longitude:                   lon(startPos.longitude, distanceDelta),
		info:                        `Сгенерированный водитель компании '${company.name}'`,
		isAutogenerated:             true
	};
	const transports: dto.TransportCreateDto[] = await generateTransports(
		faker.datatype.number({ min: 1, max: 2 }),
		driver
	);
	return { driver, transports };
}
